version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=dev_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d dev_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: ${DOCKERFILE_NAME}
    volumes:
      - ./:/app
      - ./src/lib/debug/logs:/app/src/lib/debug/logs
    ports:
      - "3000:3000"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/test_db?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy